<script lang="ts">
    export let theme: 'light' | 'dark' | undefined = undefined;
</script>

<div class="Theme {theme ? theme : ''}">
    <slot />
</div>

<style>
    .Theme {
        display: contents;
    }
    .Theme:not(.dark),
    .Theme.light {
        --base: var(--light-base);
        --bg: var(--light-bg);
        --bg-lighter: var(--light-bg-lighter);
        --bg-overlay: var(--light-bg-overlay);
        --bg-selected: var(--light-bg-selected);
        --text: var(--light-text);
        --text-light: var(--light-text-light);
        --text-lighter: var(--light-text-lighter);
        --text-lightest: var(--light-text-lightest);
        --text-placeholder: var(--light-text-placeholder);
        --hover: var(--light-hover);
        --tab-hover: var(--light-tab-hover);
        --border: var(--light-border);
        --border-alert: var(--light-border-alert);
        --border-light: var(--light-border-light);
        --border-darker: var(--light-border-darker);
        --border-alpha: var(--light-border-alpha);
        --border-alpha-dark: var(--light-border-alpha-dark);
        --border-alpha-darker: var(--light-border-alpha-darker);
        --link: var(--light-link);
        --link-hover: var(--light-link-hover);
        --link-disabled: var(--light-link-disabled);
        --button: var(--light-button);
        --button-hover: var(--light-button-hover);
        --button-text: var(--light-button-text);
        --button-text-hover: var(--light-button-text-hover);
        --button-disabled: var(--light-button-disabled);
        --button-disabled-text: var(--light-button-disabled-text);
        --button-secondary: var(--light-button-secondary);
        --button-secondary-hover: var(--light-button-secondary-hover);
        --button-secondary-text: var(--light-button-secondary-text);
        --button-secondary-text-hover: var(--light-button-secondary-text-hover);
        --button-tertiary: var(--light-button-tertiary);
        --button-tertiary-hover: var(--light-button-tertiary-hover);
        --button-tertiary-text: var(--light-button-tertiary-text);
        --button-tertiary-text-hover: var(--light-button-tertiary-text-hover);
        --button-outlined-border: var(--light-button-outlined-border);
        --button-outlined-border-hover: var(--light-button-outlined-border-hover);
        --button-outlined-text: var(--light-button-outlined-text);
        --button-outlined-text-hover: var(--light-button-outlined-text-hover);
        --button-outlined-disabled-border: var(--light-button-outlined-disabled-border);
        --button-outlined-disabled-text: var(--light-button-outlined-disabled-text);
        --button-outlined-bw-border: var(--light-button-outlined-bw-border);
        --button-outlined-bw-border-hover: var(--light-button-outlined-bw-border-hover);
        --button-outlined-bw-text: var(--light-button-outlined-bw-text);
        --button-outlined-bw-text-hover: var(--light-button-outlined-bw-text-hover);
        --toggle-on: var(--light-toggle-on);
        --toggle-off: var(--light-toggle-off);
        --toggle-on-hover: var(--light-toggle-on-hover);
        --toggle-circle-on: var(--light-toggle-circle-on);
        --toggle-circle-off: var(--light-toggle-circle-off);
        --shadow: var(--light-shadow);
        --alert-bg: var(--alert-bg);
        --alert-border: var(--alert-border);
        --alert-text: var(--alert-text);
        --alert-link: var(--alert-link);
        --alert-link-hover: var(--alert-link-hover);
        --bg-highlight: var(--bg-highlight);
        --border-highlight: var(--border-highlight);
        --text-highlight: var(--text-highlight);
        --text-lighter-highlight: var(--text-lighter-highlight);
        --focus-outline: var(--light-focus-outline);
    }
    .Theme.dark {
        --base: var(--dark-base);
        --bg: var(--dark-bg);
        --bg-lighter: var(--dark-bg-lighter);
        --bg-overlay: var(--dark-bg-overlay);
        --bg-selected: var(--dark-bg-selected);
        --text: var(--dark-text);
        --text-light: var(--dark-text-light);
        --text-lighter: var(--dark-text-lighter);
        --text-lightest: var(--dark-text-lightest);
        --text-placeholder: var(--dark-text-placeholder);
        --hover: var(--dark-hover);
        --tab-hover: var(--dark-tab-hover);
        --border: var(--dark-border);
        --border-alert: var(--dark-border-alert);
        --border-light: var(--dark-border-light);
        --border-darker: var(--dark-border-darker);
        --border-alpha: var(--dark-border-alpha);
        --border-alpha-dark: var(--dark-border-alpha-dark);
        --border-alpha-darker: var(--dark-border-alpha-darker);
        --link: var(--dark-link);
        --link-hover: var(--dark-link-hover);
        --link-disabled: var(--dark-link-disabled);
        --button: var(--dark-button);
        --button-hover: var(--dark-button-hover);
        --button-text: var(--dark-button-text);
        --button-text-hover: var(--dark-button-text-hover);
        --button-disabled: var(--dark-button-disabled);
        --button-disabled-text: var(--dark-button-disabled-text);
        --button-secondary: var(--dark-button-secondary);
        --button-secondary-hover: var(--dark-button-secondary-hover);
        --button-secondary-text: var(--dark-button-secondary-text);
        --button-secondary-text-hover: var(--dark-button-secondary-text-hover);
        --button-tertiary: var(--dark-button-tertiary);
        --button-tertiary-hover: var(--dark-button-tertiary-hover);
        --button-tertiary-text: var(--dark-button-tertiary-text);
        --button-tertiary-text-hover: var(--dark-button-tertiary-text-hover);
        --button-outlined-border: var(--dark-button-outlined-border);
        --button-outlined-border-hover: var(--dark-button-outlined-border-hover);
        --button-outlined-text: var(--dark-button-outlined-text);
        --button-outlined-text-hover: var(--dark-button-outlined-text-hover);
        --button-outlined-disabled-border: var(--dark-button-outlined-disabled-border);
        --button-outlined-disabled-text: var(--dark-button-outlined-disabled-text);
        --button-outlined-bw-border: var(--dark-button-outlined-bw-border);
        --button-outlined-bw-border-hover: var(--dark-button-outlined-bw-border-hover);
        --button-outlined-bw-text: var(--dark-button-outlined-bw-text);
        --button-outlined-bw-text-hover: var(--dark-button-outlined-bw-text-hover);
        --toggle-on: var(--dark-toggle-on);
        --toggle-off: var(--dark-toggle-off);
        --toggle-on-hover: var(--dark-toggle-on-hover);
        --toggle-circle-on: var(--dark-toggle-circle-on);
        --toggle-circle-off: var(--dark-toggle-circle-off);
        --shadow: var(--dark-shadow);
        --alert-bg: var(--dark-alert-bg);
        --alert-border: var(--dark-alert-border);
        --alert-text: var(--dark-alert-text);
        --alert-link: var(--dark-alert-link);
        --alert-link-hover: var(--dark-alert-link-hover);
        --bg-highlight: var(--dark-bg-highlight);
        --border-highlight: var(--dark-border-highlight);
        --text-highlight: var(--dark-text-highlight);
        --text-lighter-highlight: var(--dark-text-lighter-highlight);
        --focus-outline: var(--dark-focus-outline);
    }
    @media (prefers-color-scheme: dark) {
        .Theme:not(.light) {
            --base: var(--dark-base);
            --bg: var(--dark-bg);
            --bg-lighter: var(--dark-bg-lighter);
            --bg-overlay: var(--dark-bg-overlay);
            --bg-selected: var(--dark-bg-selected);
            --text: var(--dark-text);
            --text-light: var(--dark-text-light);
            --text-lighter: var(--dark-text-lighter);
            --text-lightest: var(--dark-text-lightest);
            --text-placeholder: var(--dark-text-placeholder);
            --hover: var(--dark-hover);
            --tab-hover: var(--dark-tab-hover);
            --border: var(--dark-border);
            --border-alert: var(--dark-border-alert);
            --border-light: var(--dark-border-light);
            --border-darker: var(--dark-border-darker);
            --border-alpha: var(--dark-border-alpha);
            --border-alpha-dark: var(--dark-border-alpha-dark);
            --border-alpha-darker: var(--dark-border-alpha-darker);
            --link: var(--dark-link);
            --link-hover: var(--dark-link-hover);
            --link-disabled: var(--dark-link-disabled);
            --button: var(--dark-button);
            --button-hover: var(--dark-button-hover);
            --button-text: var(--dark-button-text);
            --button-text-hover: var(--dark-button-text-hover);
            --button-disabled: var(--dark-button-disabled);
            --button-disabled-text: var(--dark-button-disabled-text);
            --button-secondary: var(--dark-button-secondary);
            --button-secondary-hover: var(--dark-button-secondary-hover);
            --button-secondary-text: var(--dark-button-secondary-text);
            --button-secondary-text-hover: var(--dark-button-secondary-text-hover);
            --button-tertiary: var(--dark-button-tertiary);
            --button-tertiary-hover: var(--dark-button-tertiary-hover);
            --button-tertiary-text: var(--dark-button-tertiary-text);
            --button-tertiary-text-hover: var(--dark-button-tertiary-text-hover);
            --button-outlined-border: var(--dark-button-outlined-border);
            --button-outlined-border-hover: var(--dark-button-outlined-border-hover);
            --button-outlined-text: var(--dark-button-outlined-text);
            --button-outlined-text-hover: var(--dark-button-outlined-text-hover);
            --button-outlined-disabled-border: var(--dark-button-outlined-disabled-border);
            --button-outlined-disabled-text: var(--dark-button-outlined-disabled-text);
            --button-outlined-bw-border: var(--dark-button-outlined-bw-border);
            --button-outlined-bw-border-hover: var(--dark-button-outlined-bw-border-hover);
            --button-outlined-bw-text: var(--dark-button-outlined-bw-text);
            --button-outlined-bw-text-hover: var(--dark-button-outlined-bw-text-hover);
            --toggle-on: var(--dark-toggle-on);
            --toggle-off: var(--dark-toggle-off);
            --toggle-on-hover: var(--dark-toggle-on-hover);
            --toggle-circle-on: var(--dark-toggle-circle-on);
            --toggle-circle-off: var(--dark-toggle-circle-off);
            --shadow: var(--dark-shadow);
            --alert-bg: var(--dark-alert-bg);
            --alert-border: var(--dark-alert-border);
            --alert-text: var(--dark-alert-text);
            --alert-link: var(--dark-alert-link);
            --alert-link-hover: var(--dark-alert-link-hover);
            --bg-highlight: var(--dark-bg-highlight);
            --border-highlight: var(--dark-border-highlight);
            --text-highlight: var(--dark-text-highlight);
            --text-lighter-highlight: var(--dark-text-lighter-highlight);
            --focus-outline: var(--dark-focus-outline);
        }
    }
</style>